@startuml 
title ドメインモデル

object ユーザー {
	ユーザーID
	名前
	メールアドレス
	パスワード
	List<スキル>
	自己紹介
	List<経歴>
}

note left
	・必須項目
	　・名前: 255文字以内(ユニーク)
	　・メールアドレス: 255文字以内
	　・パスワード: 12文字以上,英数字それぞれ最低1文字以上
	　・スキル: 複数可（1以上）
	・任意項目
	　・自己紹介: 2000文字以内
	　・経歴: 複数可（0以上）
end note

object スキル {
	スキルID
	タグID
	評価
	年数
}
note left
	・評価: 1~5
	・年数: 0以上のint型(5年まで)
end note

object 経歴 {
	経歴ID
	詳細
	西暦（from）
	西暦（to）
}
note left
	・評価: 1~5
	・年数: 0以上のint型(5年まで)
end note

ユーザー --o "1..n" スキル
ユーザー --o "0..n" 経歴

package メンター集約 {
	object メンター {
		ユーザーID
	}
}

package メンティ集約 {
	object メンティ {
		ユーザーID
	}
}
ユーザー <|-- メンター
ユーザー <|-- メンティ

package タグ集約 {
	object タグ {
		タグID
		タグ名
	}
	note right
		・タグ名：選択式、記入どちらも可
	end note
}
スキル -- "1" タグ

package メンター募集集約 {
	object メンター募集 {
		メンター募集ID
		タイトル
		カテゴリ
		相談形式
		相談方式
		ディスクリプション
		予算
		応募期間
		ステータス
		List<タグID>
	}
	note left
		・必須項目
    　・タイトル: 255文字以内
		　・カテゴリ: 一つ
    　・相談形式：単発 or 継続
    　・相談方式：チャット or ビデオ通話
    　・ディスクリプション：2000文字
    　・予算(from)：1000円以上の数値
		　・予算(to)
    　・応募期間：1日単位（最大14日後まで可能）
    　・ステータス：公開 or 中止
		・任意
		　・タグ: 複数可、選択式 or 記入
	end note
}
メンター募集 --o "0..n" タグ

package プラン集約 {
	object プラン {
		プランID
		タイトル
		カテゴリ
		タグID
		内容
		ステータス
		相談形式
		金額
		相談方式
	}
	note right
　・必須項目
　　・タイトル: 255文字以内
　　・タグ: 選択式 or 新規記入
　　・内容：2000文字以内
　　・ステータス：公開or中止
　　・相談形式：単発 or 継続
　　・金額
　・任意項目
　　・相談方式：チャットorビデオ電話
	end note
}

package プラン契約集約 {
	object プラン契約リクエスト {
		プランリクエストID
		メッセージ
		金額
	}
}
note right
	・メッセージ: 最大500文字
end note
プラン "1" --o "0..n" プラン契約リクエスト

package プラン承認集約 {
	object プラン承認 {
		プラン承認ID
		プランリクエストID
		メッセージ
	}
}
note right
	・メッセージ: 最大500文字
end note
プラン契約リクエスト "1" o-- "0..1" プラン承認

@enduml
