services:
  # MySQL
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-store:/var/lib/mysql
      - db-store:/etc/mysql/conf.d/my.cnf
      - db-store:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
volumes:
  db-store:
